name: jsaction
on: 
  push:
jobs:
  test-js-action:
    name: job to test Js action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@4
      - uses: ./
        id: jsAction
        with:
          number1: 4
          number2: 2
      - run: ${{steps.jsAction.output.result}}    